In [1]:
print("EDA")

EDA

In [2]:
import pandas as pd

df = pd.read_csv('reddit_politics_comments.csv')
df

,post_id,post_title,timestamp,platform,user_id,text,word_count,label
0,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:06:21,reddit,AutoModerator,"**As a reminder, this subreddit [is for civil ...",141,NaN
1,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:08:42,reddit,B-Z_B-S,It's a voter suppression bill. And it was writ...,23,NaN
2,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:25:06,reddit,GWFfarley2k,Pretty sure that stopping women from voting wa...,25,NaN
3,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:38:37,reddit,LuckyandBrownie,This is not meant to be a functional law. It’s...,27,NaN
4,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:12:59,reddit,No_Somewhere_7109,Thune is unwilling to remove the Filibuster to...,152,NaN
...,...,...,...,...,...,...,...,...
1716,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T15:13:21,reddit,Thebritishdovah,Probably because and I can't believe I am in f...,54,NaN
1717,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T17:48:07,reddit,RogueAOV,I always wonder how a sleeper cell actually fu...,59,NaN
1718,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T18:37:50,reddit,Bikewer,How would an even half-bright person NOT think...,30,NaN
1719,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T22:34:38,reddit,InsomniaticWanderer,So we have no idea where Trump is?\n\nBecause ...,18,NaN
1720,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-11T00:54:44,reddit,simmons777,"Too late to hide that threat, I'm pretty sure ...",16,NaN

In [5]:
df['user_id'].value_counts()

user_id
AutoModerator           56
raiansar                15
B-Z_B-S                  8
Historical_Bend_2629     6
Memitim                  5
                        ..
Colonel-Mooseknuckle     1
Dimitri3p0               1
cybah                    1
bryce_lynch27            1
simmons777               1
Name: count, Length: 1471, dtype: int64

In [13]:
import re 

def clean_text(text):

    if pd.isna(text):
        return ""

    # lowercase
    text = text.lower()

    # remove newline
    text = text.replace("\n", " ")

    # remove url
    text = re.sub(r"http\S+", "", text)

    # remove special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)

    # remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

def transform_data(input_path, output_path):

    df = pd.read_csv(input_path)

    # cleaning comment
    df["comment_clean"] = df["text"].apply(clean_text)

    # remove empty comment
    df = df[df["comment_clean"] != ""]

    # remove duplicate comment
    df = df.drop_duplicates(subset=["comment_clean"])

    df = df[
    (df["user_id"] != "AutoModerator") &
    (df["user_id"] != "[deleted]") &
    (df["user_id"] != "[removed]")
    ]

    # reset index
    df = df.reset_index(drop=True)

    # save cleaned data
    df.to_csv(output_path, index=False)

    print("Cleaning selesai")
    print("Jumlah data:", len(df))

In [14]:
transform_data(
    "reddit_politics_comments.csv",
    "reddit_comments_clean.csv"
)

Cleaning selesai
Jumlah data: 1665

In [15]:
df_cleaned = pd.read_csv('reddit_comments_clean.csv')
df_cleaned

,post_id,post_title,timestamp,platform,user_id,text,word_count,label,comment_clean
0,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:08:42,reddit,B-Z_B-S,It's a voter suppression bill. And it was writ...,23,NaN,its a voter suppression bill and it was writte...
1,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:25:06,reddit,GWFfarley2k,Pretty sure that stopping women from voting wa...,25,NaN,pretty sure that stopping women from voting wa...
2,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:38:37,reddit,LuckyandBrownie,This is not meant to be a functional law. It’s...,27,NaN,this is not meant to be a functional law its m...
3,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:12:59,reddit,No_Somewhere_7109,Thune is unwilling to remove the Filibuster to...,152,NaN,thune is unwilling to remove the filibuster to...
4,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:36:47,reddit,PolicyWonka,Forcing tens of millions of Americans to go to...,38,NaN,forcing tens of millions of americans to go to...
...,...,...,...,...,...,...,...,...,...
1660,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T15:13:21,reddit,Thebritishdovah,Probably because and I can't believe I am in f...,54,NaN,probably because and i cant believe i am in fa...
1661,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T17:48:07,reddit,RogueAOV,I always wonder how a sleeper cell actually fu...,59,NaN,i always wonder how a sleeper cell actually fu...
1662,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T18:37:50,reddit,Bikewer,How would an even half-bright person NOT think...,30,NaN,how would an even halfbright person not think ...
1663,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T22:34:38,reddit,InsomniaticWanderer,So we have no idea where Trump is?\n\nBecause ...,18,NaN,so we have no idea where trump is because that...
1664,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-11T00:54:44,reddit,simmons777,"Too late to hide that threat, I'm pretty sure ...",16,NaN,too late to hide that threat im pretty sure ev...

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

texts = df_cleaned["text"]

# TF-IDF
vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X = vectorizer.fit_transform(texts)

# KMeans clustering
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

df_cleaned["cluster"] = kmeans.fit_predict(X)
df_cleaned

,post_id,post_title,timestamp,platform,user_id,text,word_count,label,comment_clean,cluster
0,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:08:42,reddit,B-Z_B-S,It's a voter suppression bill. And it was writ...,23,NaN,its a voter suppression bill and it was writte...,2
1,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:25:06,reddit,GWFfarley2k,Pretty sure that stopping women from voting wa...,25,NaN,pretty sure that stopping women from voting wa...,2
2,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:38:37,reddit,LuckyandBrownie,This is not meant to be a functional law. It’s...,27,NaN,this is not meant to be a functional law its m...,0
3,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:12:59,reddit,No_Somewhere_7109,Thune is unwilling to remove the Filibuster to...,152,NaN,thune is unwilling to remove the filibuster to...,2
4,1rq7t5p,Leavitt Admits SAVE Act Will Make It Harder fo...,2026-03-10T20:36:47,reddit,PolicyWonka,Forcing tens of millions of Americans to go to...,38,NaN,forcing tens of millions of americans to go to...,2
...,...,...,...,...,...,...,...,...,...,...
1660,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T15:13:21,reddit,Thebritishdovah,Probably because and I can't believe I am in f...,54,NaN,probably because and i cant believe i am in fa...,1
1661,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T17:48:07,reddit,RogueAOV,I always wonder how a sleeper cell actually fu...,59,NaN,i always wonder how a sleeper cell actually fu...,1
1662,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T18:37:50,reddit,Bikewer,How would an even half-bright person NOT think...,30,NaN,how would an even halfbright person not think ...,1
1663,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-10T22:34:38,reddit,InsomniaticWanderer,So we have no idea where Trump is?\n\nBecause ...,18,NaN,so we have no idea where trump is because that...,2
1664,1rpw74x,Trump Goons Ordered to Hide Major Threat From ...,2026-03-11T00:54:44,reddit,simmons777,"Too late to hide that threat, I'm pretty sure ...",16,NaN,too late to hide that threat im pretty sure ev...,2

In [22]:
for i, row in df_cleaned.head(20).iterrows():

    print("Comment :", row["text"])
    print("Label   :", row["cluster"])
    print("-"*50)

Comment : It's a voter suppression bill. And it was written to allow the Republican Party to win the midterms even with their extreme unpopularity.
Label   : 2
--------------------------------------------------
Comment : Pretty sure that stopping women from voting was another thing in Project2025. You know the one trump never heard of but is following almost exactly.
Label   : 2
--------------------------------------------------
Comment : This is not meant to be a functional law. It’s meant to throw the election into chaos with no one knowing what the fuck is going on.
Label   : 0
--------------------------------------------------
Comment : Thune is unwilling to remove the Filibuster to push it through, fortunately, and they don't have the votes besides. Trump may not be around long but most of the Senate will be and they know that there's no jamming the genie back in the bottle if the follow through - eventually the Democrats *will* get control again in some form and the Republicans will be lame ducks with no ability to stonewall.

Even removing it then putting it back utterly destroys the Filibuster's power and it ceases to be something neither party wants to touch. If the Republicans do it now and try to put it back afterwards, the Dems will just do it themselves next time without fear.

I'm sure that Thune also knows the last time the GOP tried to push this sort of thing through on a state level it ratfucked Republican voters so badly they rolled it back.
Label   : 2
--------------------------------------------------
Comment : Forcing tens of millions of Americans to go to the DMV to present proof of name change and citizenship to register to vote? For an election that begins early voting in basically 6 months?

What could go wrong?
Label   : 2
--------------------------------------------------
Comment : Talk about shooting yourself in the foot. Which party is more likely to have preferred to be single and/or married women who go by their original surname and which party is more likely to have women who take on their husband's name "like the way God intended?" aka the Tradwife way?
Label   : 2
--------------------------------------------------
Comment : another day another republican trying to suppress the vote because they know they cant win fair and square
Label   : 2
--------------------------------------------------
Comment : So, for women who have changed their names from their birth names, if they are currently registered to vote do they need to do anything?  Or is it only if they move and have to re-register in a new location?  Just curious about how crazy this really is.

(just in case it needs to be said, fuck this administration)
Label   : 1
--------------------------------------------------
Comment : I’m female. I’m married. I’m also adopted as a teen. I have two birth certificates. When I’m fingerprinted to work at schools, it might take them 15-20 minutes to review, understand, and approve my paperwork.

This bullshit will create the longest lines on voting day. People who work the polls are not experts in all documents spanning 10+ decades issued in all states. Is the birth certificate required to be notarized? If the paper is too worn, will it be permitted? How will they treat copies of birth certificates or marriage certificates?

They withheld my husband’s vote last year because they questioned his signature. When we looked at the signatures being compared, it was laughable. He completed the extra step to get his vote counted, but I have to wonder if they were randomly selecting all voters or just targeting democratic ones.
Label   : 2
--------------------------------------------------
Comment : For women: never legally change your name. They will weaponize it against you

You have no legal obligation to change your name when getting married
Label   : 2
--------------------------------------------------
Comment : She’s no doubt stoked about that. She’s a fucking weirdo who loves wrinkly ball sacks.
Label   : 2
--------------------------------------------------
Comment : 'When conservatives can no longer win elections on their policies, they will not abandon conservatism, they will abandon democracy.'
Label   : 2
--------------------------------------------------
Comment : But in maga world the husbands vote counts for both, she just needs to keep an eye on the chicken and tend to the children.

Any women still supporting trump and the cons deserves to be treated like second class it's what they want right.
Label   : 1
--------------------------------------------------
Comment : I encourage everyone here to get their passports or get them renewed if needed. Although I don't think this law will pass, if it does, the sudden rush might make it very hard to get this done before election time.
Label   : 2
--------------------------------------------------
Comment : I was indifferent whether or not my wife took my name when we got married. Now I'm absolutely gleeful she didn't.
Label   : 2
--------------------------------------------------
Comment : Republicans don’t want kids to read The Handmaid’s Tale in school - they want kids to experience the live action immersive experience.
Label   : 2
--------------------------------------------------
Comment : By "make it harder to vote" what she actually means is "disenfeanchise millions of Americans".

If it passes Im going to start a charity whose only purpose will be to help people disenfranchised by this *stupid fucking bill* to get to where they need to be in order to register to vote and then PAY THE DAMN PROCESSING FEES so they can actually get it done.
Label   : 2
--------------------------------------------------
Comment : May backfire on them because republican women are more likely to marry than democrat women, and republican women are more likely to change their name when they do marry than democrat women.
So they are screwing themselves because it will affect republicans more than democrats in general. Its also harder for rural republicans to re-register than in city where more democrats live.
Label   : 2
--------------------------------------------------
Comment : Ladies, if you're voting republican I just don't get you. This is beyond suppression. They HATE women
Label   : 1
--------------------------------------------------
Comment : So my democratic female friends on whole have a passport. My republican female friends (actually just mainly family) on a whole do not have a passport. So there is that.
Label   : 1
--------------------------------------------------

In [23]:
df_cleaned['cluster'].value_counts()

cluster
2    1280
1     246
0     139
Name: count, dtype: int64