In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("../data/raw/reddit_raw_comments_V1_2026-04-04.csv")
df_raw.head()

,post_id,post_title,subreddit,timestamp,platform,user_id,text,word_count,depth,label
0,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T00:51:34,reddit,AutoModerator,"**As a reminder, this subreddit [is for civil ...",141,0,NaN
1,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T02:21:09,reddit,Juicecalculator,He is exposed. There is enough evidence to pu...,16,1,NaN
2,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T03:10:14,reddit,LochNessMansterLives,"And yet, nobody is doing anything but a few ju...",61,2,NaN
3,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T10:13:14,reddit,Church_of_Aaargh,Everybody is scared of the bullies and what th...,25,3,NaN
4,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T08:40:33,reddit,SoberButterfly,I say it all the time: at this point our main ...,40,3,NaN

In [3]:
df = pd.read_csv('../data/processed/reddit_clean_comments_V2_2026-04-04.csv')
df.head()

,post_id,post_title,subreddit,timestamp,platform,user_id,text,word_count,depth,label,comment_clean,embedding,confidence
0,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T02:21:09,reddit,Juicecalculator,He is exposed. There is enough evidence to pu...,16,1,Neutral,he is exposed there is enough evidence to put ...,"[0.0784972682595253, 0.049813348799943924, -0....",0.6117
1,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T03:10:14,reddit,LochNessMansterLives,"And yet, nobody is doing anything but a few ju...",61,2,Neutral,and yet nobody is doing anything but a few jud...,"[0.08909966051578522, 0.021278096362948418, -0...",0.7867
2,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T10:13:14,reddit,Church_of_Aaargh,Everybody is scared of the bullies and what th...,25,3,Neutral,everybody is scared of the bullies and what th...,"[0.020719533786177635, 0.051325175911188126, -...",0.7233
3,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T08:40:33,reddit,SoberButterfly,I say it all the time: at this point our main ...,40,3,Neutral,i say it all the time at this point our main o...,"[0.031099602580070496, -0.02745627425611019, 0...",0.9824
4,1sbv676,"Key Details Trump Accuser, 13, Told FBI Were C...",politics,2026-04-04T09:07:46,reddit,Star_Denizen,"&gt; for life. \n\nEven if trump was arrested,...",27,2,Neutral,gt for life even if trump was arrested tried c...,"[0.013707331381738186, 0.06963600218296051, 0....",0.7478

In [4]:
df['subreddit'].value_counts()

subreddit
politics            67
worldnews           65
unpopularopinion    65
Name: count, dtype: int64

In [5]:
df['user_id'].value_counts()

user_id
Melinoe2016             6
XxDJXSonaxX             4
HowManyEggs2Many        3
Interesting-Nerve646    3
HauntedCemetery         3
                       ..
LughCrow                1
Jung-And-A-Menace       1
erickson666             1
Mattock1987             1
Klolok                  1
Name: count, Length: 157, dtype: int64

In [6]:
df.shape

(197, 13)

In [7]:
df_raw['text']

0      **As a reminder, this subreddit [is for civil ...
1      He is exposed.  There is enough evidence to pu...
2      And yet, nobody is doing anything but a few ju...
3      Everybody is scared of the bullies and what th...
4      I say it all the time: at this point our main ...
                             ...
195    All liver is gross. Why would anyone think a f...
196    I went to university in a spot that had the la...
197    idk man organ meats kinda hit different but st...
198    Shii this sounds good asf. Im not a fan of giz...
199    Grew up in an Asian household. It was awesome ...
Name: text, Length: 200, dtype: object

In [8]:
for i, row in df[21:50].iterrows():

    print("Comment :", row["text"], '|', row['label'])
    print("-"*50)

Comment : Idk if he rigged the swing states but it'd be a lot harder to rig a giant state like California that hates his guts. I do think he'll try to steal the election some other way | Neutral
--------------------------------------------------
Comment : That depends if cali dems can get their shit together. They have a jungle primary and the top 2 candidates get on the ballot for governor. Currently the top 2 in polling are both Republicans, because there are like a dozen dems running and they all refuse to step down and consolidate. | Neutral
--------------------------------------------------
Comment : I promise you no conservative is winning the California governor election. People here hate trump, now more than ever | uncertain
--------------------------------------------------
Comment : Agreed, and I think Arnold isn't crazy enough to be a modern day conservative anyway lol | Neutral
--------------------------------------------------
Comment : 100%, he's had videos come out condemning DJT's actions.  One notable one I remember was from the J6 attempted coup. | Neutral
--------------------------------------------------
Comment : Now now, Trump doesnt always attack foreign countries to avert attention. He can also throw some stooge under a bus as distraction. | Neutral
--------------------------------------------------
Comment : I’m sure you don’t realize the impact that threat has had on your longest and closest former allies. | Neutral
--------------------------------------------------
Comment : You can try, but if you think that the gas price is your biggest worry, then wait and see what happens when we start threatening to dump US Treasury Bonds. | Neutral
--------------------------------------------------
Comment : sounds like enabling  and youre defending the abusers

crit·i·cism
1.
the expression of disapproval of someone or something based on perceived faults or mistakes.
"he received a lot of criticism"

2.
the analysis and judgment of the merits and faults of a literary or artistic work.
"alternative methods of criticism supported by well-developed literary theories"

yall just offering suggestions to hurt others? look at how society has been rotting due to people making sick jokes''for the lolz'' instead of using language to oppose and dismantle/stop the nonsense | Offensive
--------------------------------------------------
Comment : You seriously just stretched a criticism into somehow being pro trump


Talk about bad jokes. | Neutral
--------------------------------------------------
Comment : So when I was deployed and getting attacked with IEDs multiple times a week, and I joked about making a parody Mentos commercial where an insurgent can't get his detonator circuit to work, but he pops a Mento and inspiration strikes, and he starts taking apart a Walkman for parts and gets the circuit working, and when he mugs to the camera holding the pack of Mentos we hear an explosion off-screen, and when the voiceover says "Mentos, the freshmaker" then out of focus in the background a HMMWV rolls through the frame on fire...

...that would have been disgusting to you? | Neutral
--------------------------------------------------
Comment : I can step out on my front porch and point to all of their houses, unfortunately… | Neutral
--------------------------------------------------
Comment : Amusingly Blanche has already indicated an intention to commit crimes and breach the law requiring him to release the unredacted files and the remaining files they are sitting on illegally. | Neutral
--------------------------------------------------
Comment : “Well, technically he’s the *ACTING* Attorney General, not the Attorney General, so that law doesn’t apply to him. Please go ahead and sue us so we can drag it out in court for the next 3 years.” - DJT’s crackshot team of lawyers | Neutral
--------------------------------------------------
Comment : And im *acting* surprised when all the documents relating epsteing are shredded because he's a pedophile's lawyer | Offensive
--------------------------------------------------
Comment : We all know the president is a child rapist, why is nothing being done by the people whos job it is to do something about it. | Offensive
--------------------------------------------------
Comment : I have the same questions as you do.

If I’m honest, I don’t think there will be any accountability.

Another commenter said it’s because the ones who would be in a position to bring justice are sold out to “money and power”.

I don’t think that’s the only issue.

I think it’s just because bringing powerful people to justice is a lot more work than anyone is willing to put in, it can have life threatening consequences and requires ideological motivation. | Neutral
--------------------------------------------------
Comment : The Republicans went “all in” on MAGA. Trump is their standard bearer, patrimonial father, their supreme leader, and now their God. Attacking him would be like attacking Christ himself. The Democrats are lame ducks at the moment, and if they do regain power, and that’s a big IF in a competitive authoritarian election, they are going to have their work cut out for them across an almost infinite number of problems to address. It’s why “flood the zone” is so effective. I do think that this is so egregious that it should sit at the very top of the list (above the economy and even the war). He must be brought to justice while he’s alive. We will see. | uncertain
--------------------------------------------------
Comment : If accountability and justice were ever going to happen, it would have been when this shit was reported - years and years ago.

That should tell you who else is complicit in all this, and how long they've been deliberately avoiding carrying out justice. | Neutral
--------------------------------------------------
Comment : I know its obvious but it just seems like it sometimes needs to be plainly stated. It really feels like the government hates us and everyone else. Fuck these assholes. | Offensive
--------------------------------------------------
Comment : Because the American people entirely removed the only people willing to do anything about it from federal power and are now hating on them for not fixing our problems despite having literally no federal power. | Neutral
--------------------------------------------------
Comment : I mean, it’s documented in the court that he is an adjudicated rapist. Also convicted for 37 felonies.

America: thats my man!!! I’m going to vote him as president 🤪

Batshit insanity | Offensive
--------------------------------------------------
Comment : Considering they redacted the word Dont on multiple pages, its pretty clear theyre protecting a famous politician who's first name and first letter of their last name spell that word. | Neutral
--------------------------------------------------
Comment : Kinda poetic though, that a rapist's name would literally spell "don't". If this were in a movie, it'd be too on the nose, yet here we are.


Honestly, if the last 10 years of American politics was in a movie, I'd be rolling my eyes at how ridiculous it would be that we, the audience, are expected to believe that anyone would vote for a dude with ZERO political career as president, and certainly not for a second term after being a 37x convicted felon, fraud, and known child rapist.


In the same cinematic universe where Bill Clinton was cancelled over a blowjob between two consenting adults? I don't think so. 0/10 for believability. | Offensive
--------------------------------------------------
Comment : Like its clear they redacted "Dont", which has no business being redacted in any context unless they were flagging Don T in a hasty attempt to scrub his name. | Neutral
--------------------------------------------------
Comment : Yes. There are places where "don't" and sentences ending in "don." and the next sentence starting with a "T" have been redacted.  I do not have links to them handy on this computer, but I'm sure some deft search work would find them, or someone will show up eventually with a link or three. | Neutral
--------------------------------------------------
Comment : Not that it changes much, but it isn’t a child’s testimony, the woman was a fully grown adult when she met with the FBI. These interviews were in 2019 for an event that happened in 1984. | Neutral
--------------------------------------------------
Comment : While sickening nonetheless, this is the testimony of that victim from when she was a child, not at the time of the event when she was a child. | Neutral
--------------------------------------------------
Comment : It won't they aren't planning to leave. As a matter of fact they're doing everything in their power to make sure they don't leave. I feel bad for you Americans but it's going to I have to be a violent overthrow. And they'll see you coming a mile away because all of that social media opinion that you post online has put you in a database. Right now they use that list to try to deny your vote, and in the future they'll use that list to deny you government services, deny you the right to travel and eventually round you up if you keep up your opinion. | uncertain
--------------------------------------------------

In [35]:
from tabulate import tabulate

df_compare = pd.DataFrame({
    "Raw Text": df_raw["text"].iloc[21:30].values,
    "Cleaned Text": df["text"].iloc[21:30].values
})

print(tabulate(df_compare, headers="keys", tablefmt="grid"))

+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|    | Raw Text                                                                                                                                                                                                                                                                                      | Cleaned Text                                                                                                                                                                                                                                                                                  |
+====+===============================================================================================================================================================================================================================================================================================+===============================================================================================================================================================================================================================================================================================+
|  0 | I'm implying they'll rig it. Just like he won *all* of the swing states. Every single one.                                                                                                                                                                                                    | Idk if he rigged the swing states but it'd be a lot harder to rig a giant state like California that hates his guts. I do think he'll try to steal the election some other way                                                                                                                |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  1 | Idk if he rigged the swing states but it'd be a lot harder to rig a giant state like California that hates his guts. I do think he'll try to steal the election some other way                                                                                                                | That depends if cali dems can get their shit together. They have a jungle primary and the top 2 candidates get on the ballot for governor. Currently the top 2 in polling are both Republicans, because there are like a dozen dems running and they all refuse to step down and consolidate. |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  2 | That depends if cali dems can get their shit together. They have a jungle primary and the top 2 candidates get on the ballot for governor. Currently the top 2 in polling are both Republicans, because there are like a dozen dems running and they all refuse to step down and consolidate. | I promise you no conservative is winning the California governor election. People here hate trump, now more than ever                                                                                                                                                                         |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  3 | I promise you no conservative is winning the California governor election. People here hate trump, now more than ever                                                                                                                                                                         | Agreed, and I think Arnold isn't crazy enough to be a modern day conservative anyway lol                                                                                                                                                                                                      |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  4 | Agreed, and I think Arnold isn't crazy enough to be a modern day conservative anyway lol                                                                                                                                                                                                      | 100%, he's had videos come out condemning DJT's actions.  One notable one I remember was from the J6 attempted coup.                                                                                                                                                                          |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  5 | 100%, he's had videos come out condemning DJT's actions.  One notable one I remember was from the J6 attempted coup.                                                                                                                                                                          | Now now, Trump doesnt always attack foreign countries to avert attention. He can also throw some stooge under a bus as distraction.                                                                                                                                                           |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  6 | I’m sure you don’t realize the impact that threat has had on your longest and closest former allies.                                                                                                                                                                                          | I’m sure you don’t realize the impact that threat has had on your longest and closest former allies.                                                                                                                                                                                          |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  7 | Now now, Trump doesnt always attack foreign countries to avert attention. He can also throw some stooge under a bus as distraction.                                                                                                                                                           | You can try, but if you think that the gas price is your biggest worry, then wait and see what happens when we start threatening to dump US Treasury Bonds.                                                                                                                                   |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  8 | sounds like enabling  and youre defending the abusers                                                                                                                                                                                                                                         | sounds like enabling  and youre defending the abusers                                                                                                                                                                                                                                         |
|    |                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                               |
|    | crit·i·cism                                                                                                                                                                                                                                                                                   | crit·i·cism                                                                                                                                                                                                                                                                                   |
|    | 1.                                                                                                                                                                                                                                                                                            | 1.                                                                                                                                                                                                                                                                                            |
|    | the expression of disapproval of someone or something based on perceived faults or mistakes.                                                                                                                                                                                                  | the expression of disapproval of someone or something based on perceived faults or mistakes.                                                                                                                                                                                                  |
|    | "he received a lot of criticism"                                                                                                                                                                                                                                                              | "he received a lot of criticism"                                                                                                                                                                                                                                                              |
|    |                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                               |
|    | 2.                                                                                                                                                                                                                                                                                            | 2.                                                                                                                                                                                                                                                                                            |
|    | the analysis and judgment of the merits and faults of a literary or artistic work.                                                                                                                                                                                                            | the analysis and judgment of the merits and faults of a literary or artistic work.                                                                                                                                                                                                            |
|    | "alternative methods of criticism supported by well-developed literary theories"                                                                                                                                                                                                              | "alternative methods of criticism supported by well-developed literary theories"                                                                                                                                                                                                              |
|    |                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                               |
|    | yall just offering suggestions to hurt others? look at how society has been rotting due to people making sick jokes''for the lolz'' instead of using language to oppose and dismantle/stop the nonsense                                                                                       | yall just offering suggestions to hurt others? look at how society has been rotting due to people making sick jokes''for the lolz'' instead of using language to oppose and dismantle/stop the nonsense                                                                                       |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+